//
//  Language.swift
//  VOID
//
//  Created by GE-Developer
//

enum Language: String, CaseIterable, Identifiable {
    case english = "en"
    case arabic = "ar"
    case armenian = "hy"
    case azerbaijani = "az"
    case belarusian = "be"
    case bengali = "bn"
    case catalan = "ca"
    case chineseSimplified = "zh-Hans"
    case chineseTraditional = "zh-Hant"
    case croatian = "hr"
    case czech = "cs"
    case danish = "da"
    case dutch = "nl"
    case finnish = "fi"
    case french = "fr"
    case georgian = "ka"
    case german = "de"
    case greek = "el"
    case hebrew = "he"
    case hindi = "hi"
    case hungarian = "hu"
    case icelandic = "is"
    case indonesian = "id"
    case italian = "it"
    case japanese = "ja"
    case kazakh = "kk"
    case korean = "ko"
    case kyrgyz = "ky"
    case malay = "ms"
    case mongolian = "mn"
    case norwegian = "no"
    case persian = "fa"
    case polish = "pl"
    case portuguese = "pt"
    case romanian = "ro"
    case russian = "ru"
    case slovak = "sk"
    case spanish = "es"
    case swahili = "sw"
    case swedish = "sv"
    case tajik = "tg"
    case thai = "th"
    case turkish = "tr"
    case turkmen = "tk"
    case ukrainian = "uk"
    case urdu = "ur"
    case uzbek = "uz"
    case vietnamese = "vi"
    
    var id: String { rawValue }
    
    var localizedName: String {
        switch self {
        case .english: return "English"
        case .arabic: return "العربية"
        case .armenian: return "Հայերեն"
        case .azerbaijani: return "Azərbaycan dili"
        case .belarusian: return "Беларуская"
        case .bengali: return "বাংলা"
        case .catalan: return "Català"
        case .chineseSimplified: return "简体中文"
        case .chineseTraditional: return "繁體中文"
        case .croatian: return "Hrvatski"
        case .czech: return "Čeština"
        case .danish: return "Dansk"
        case .dutch: return "Nederlands"
        case .finnish: return "Suomi"
        case .french: return "Français"
        case .georgian: return "ქართული"
        case .german: return "Deutsch"
        case .greek: return "Ελληνικά"
        case .hebrew: return "עברית"
        case .hindi: return "हिन्दी"
        case .hungarian: return "Magyar"
        case .icelandic: return "Íslenska"
        case .indonesian: return "Bahasa Indonesia"
        case .italian: return "Italiano"
        case .japanese: return "日本語"
        case .kazakh: return "Қазақ тілі"
        case .korean: return "한국어"
        case .kyrgyz: return "Кыргызча"
        case .malay: return "Bahasa Melayu"
        case .mongolian: return "Монгол хэл"
        case .norwegian: return "Norsk"
        case .persian: return "فارسی"
        case .polish: return "Polski"
        case .portuguese: return "Português"
        case .romanian: return "Română"
        case .russian: return "Русский"
        case .slovak: return "Slovenčina"
        case .spanish: return "Español"
        case .swahili: return "Kiswahili"
        case .swedish: return "Svenska"
        case .tajik: return "Тоҷикӣ"
        case .thai: return "ไทย"
        case .turkish: return "Türkçe"
        case .turkmen: return "Türkmen dili"
        case .ukrainian: return "Українська"
        case .urdu: return "اردو"
        case .uzbek: return "O'zbek tili"
        case .vietnamese: return "Tiếng Việt"
        }
    }
    
    var englishName: String {
        switch self {
        case .english: return "English"
        case .arabic: return "Arabic"
        case .armenian: return "Armenian"
        case .azerbaijani: return "Azerbaijani"
        case .belarusian: return "Belarusian"
        case .bengali: return "Bengali"
        case .catalan: return "Catalan"
        case .chineseSimplified: return "Chinese (Simplified)"
        case .chineseTraditional: return "Chinese (Traditional)"
        case .croatian: return "Croatian"
        case .czech: return "Czech"
        case .danish: return "Danish"
        case .dutch: return "Dutch"
        case .finnish: return "Finnish"
        case .french: return "French"
        case .georgian: return "Georgian"
        case .german: return "German"
        case .greek: return "Greek"
        case .hebrew: return "Hebrew"
        case .hindi: return "Hindi"
        case .hungarian: return "Hungarian"
        case .icelandic: return "Icelandic"
        case .indonesian: return "Indonesian"
        case .italian: return "Italian"
        case .japanese: return "Japanese"
        case .kazakh: return "Kazakh"
        case .korean: return "Korean"
        case .kyrgyz: return "Kyrgyz"
        case .malay: return "Malay"
        case .mongolian: return "Mongolian"
        case .norwegian: return "Norwegian"
        case .persian: return "Persian"
        case .polish: return "Polish"
        case .portuguese: return "Portuguese"
        case .romanian: return "Romanian"
        case .russian: return "Russian"
        case .slovak: return "Slovak"
        case .spanish: return "Spanish"
        case .swahili: return "Swahili"
        case .swedish: return "Swedish"
        case .tajik: return "Tajik"
        case .thai: return "Thai"
        case .turkish: return "Turkish"
        case .turkmen: return "Turkmen"
        case .ukrainian: return "Ukrainian"
        case .urdu: return "Urdu"
        case .uzbek: return "Uzbek"
        case .vietnamese: return "Vietnamese"
        }
    }
}
